### ISSUE TITLE
Release for PHP 7.4

### ISSUE THREAD

**Issue by phil-davis** [sabre-io/cache#23]
Should a release be done to officially record support for PHP 7.4?

(I don't think any real code needed to be touched, so actually the current release would work fine with PHP 7.4)

**Comment by staabm** [comment]
Absolutely.  Feel free to create a release when time allows

**Comment by phil-davis** [comment]
I missed this until now:

https://github.com/sabre-io/cache/releases/tag/1.0.2

Release 1.0.2 is done.

I will prepare some testing to support PHP 8.0 ...
