### ISSUE TITLE
$key is not interpolated

### ISSUE THREAD

**Issue by dvikan** [sabre-io/cache#34]
https://github.com/sabre-io/cache/blob/042e4b24cea4347321739bc5470e78749bc27ffe/lib/Memcached.php#L81

**Comment by staabm** [comment]
Could you elaborate a bit?

**Comment by dvikan** [comment]
Ah my mistake.

I thought the intention was to include the content of `$key` but I see now that you always want the literal string `'$key must be a string'`.

**Comment by staabm** [comment]
> Edit: do you know why they didnt type hint string in the psr interface?

I guess not all cache backends necessarily use only strings as cache-keys.

will close the issue for now, feel free to ask further related questions
